# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnzorApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AnzorApp

  target 'AnzorApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnzorAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AnzorApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AnzorApp-tvOS

  target 'AnzorApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
